name: CI/CD Pipeline for Selenium Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install necessary packages including Selenium

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests  # Run unit tests located in the "tests" directory

      - name: Run Selenium Test
        env:
          SENDER_EMAIL: ${{ secrets.GMAIL_EMAIL }}  # Set your Gmail email in GitHub Secrets
          SENDER_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}  # Set your Gmail app password in GitHub Secrets
          RECIPIENT_EMAIL: "jeba@nidrive.in"  # Change to the recipient email as needed
        run: |
          python selenium_test.py  # Run your Selenium test script

      - name: Notify Deployment Success
        if: success()  # Only notify if the previous steps were successful
        run: |
          echo "All tests passed! Notifying via email..."  # You can include email notification logic here

      - name: Notify Deployment Failure
        if: failure()  # Notify if there was a failure in the tests
        run: |
          echo "Some tests failed. Please check the logs."  # You can include email notification logic here

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test  # This job depends on the build_and_test job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Deploying to server..."  # Replace with your actual deployment commands

      - name: Notify Deployment Success
        run: |
          echo "Deployment successful!"  # Add your email notification for successful deployment here
