name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * 1-6"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest  # Using Selenium Chrome standalone service
        ports:
          - 4444:4444  # Expose the Selenium server port

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Match your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          # Wait for Selenium service to be ready
          sleep 10  # Adjust if necessary
          python test_google.py > test_results.log || exit 0
          cat test_results.log    # Display test results for debugging

      - name: Archive Test Report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-report
          path: report.html

      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.log

      - name: Check if tests passed
        run: |
          if grep -q "FAILED" test_results.log; then
            echo "Some tests failed."
            exit 1  # Ensure the workflow fails if any test fails
          else
            echo "All tests passed."
          fi
