on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "wget --spider --timeout=5 http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt is in the root
      - name: Build Docker image
        run: |
          docker build -t my-selenium-app:latest .
      - name: Run Docker image
        run: |
          docker run -d -p 4444:4444 my-selenium-app:latest
      - name: Run Selenium tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
        run: |
          pytest --maxfail=5 --disable-warnings 


