name: Run Selenium Tests and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "wget --spider --timeout=5 http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt is in the root

      - name: Check Docker version
        run: docker --version

      - name: Build Docker image
        run: |
          docker build -t my-selenium-app:latest .  # Build the Docker image

      

      

      - name: Save docker image
        run: docker image save my-selenium-app:latest | xz -z -e -7 -T0 > selenium.xz

      - name: List Files
        run: ls -la  # Verify that selenium.xz was created

  

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}  # Use the run number as the version tag
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available in Actions

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: selenium.xz  # Path to the compressed Docker image
          asset_name: selenium.xz
          asset_content_type: application/x-xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selenium tests
        env:
            SELENIUM_URL: http://localhost:4444/wd/hub  # Selenium WebDriver URL
        run: |
            # Make sure the Selenium test script is in your repository and the test runner (pytest or similar) is set up
            pytest --maxfail=5 --disable-warnings > test_results.log  # Automatically runs your Selenium tests and logs output
      
      - name: Show test results log
        run: |
            cat test_results.log  # Output the test results in the log for debugging purposes
    