name: Run Selenium Tests and Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Grants permission to write to the repository
  actions: read    # Grants permission to read actions

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          pytest --maxfail=5 --disable-warnings > test_results.log

      - name: Compress Test Results
        run: |
          tar -cvf selenium.tar test_results.log  # Create a tarball of the log file
          xz selenium.tar  # Compress it to a .xz file

      - name: List files
        run: ls -la  # Check to ensure the selenium.xz file was created

  release:
    runs-on: ubuntu-latest
    needs: test  # This job waits for the 'test' job to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release  # Give the step an ID to refer to it later
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}  # Version the release with the run number
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the release URL
          asset_path: selenium.tar.xz  # Path to the file you want to upload
          asset_name: selenium.tar.xz  # The name the file will have in the release
          asset_content_type: application/x-xz  # Content type for the .xz file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the GitHub token is set


