name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "wget --spider --timeout=5 http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt is in the root

      - name: Run All Selenium Tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub  # Selenium WebDriver URL
        run: |
          pytest tests/ --maxfail=5 --disable-warnings -v  # Run all tests in the tests directory

      - name: Show test results log
        run: cat test_results.log  # Output the test results in the log for debugging purposes

      - name: Run Additional Test Cases
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
        run: |
          pytest additional_tests/ --maxfail=3 --disable-warnings -v  # Run additional tests from a different directory

      - name: Run Performance Tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
        run: |
          pytest performance_tests/ --maxfail=2 --disable-warnings -v  # Run performance tests if applicable
