name: Run Selenium Tests

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1280x1024x16 &
        env:
          DISPLAY: ":99"

      - name: Run Selenium script
        run: |
          python test_google.py > test_results.log || exit 0
          cat test_results.log

        

