name: Run Selenium Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pytest pytest-html selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/

    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings --html=report.html > test_results.log
        cat test_results.log  # Print the log output

          echo "/usr/lib/chromium-browser/chromedriver" >> $GITHUB_PATH
          export DISPLAY=:99.0  # Use Xvfb to run Chrome in a virtual display
