name: Run Selenium Tests

# Run the workflow whenever code is pushed or a pull request is created
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Define the environment
    runs-on: ubuntu-latest
    
    services:
      # Setup Selenium standalone Chrome using Docker
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Selenium tests using pytest
    - name: Run Selenium tests
      env:
        SELENIUM_URL: http://localhost:4444/wd/hub
      run: |
        pytest --maxfail=5 --disable-warnings
