name: Run Selenium Tests2

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1280x1024x16 &
        env:
          DISPLAY: ":99"

      - name: Run Selenium script
        run: |
          python test_google.py > test_results.log || exit 0
          cat test_results.log
      

      - name: Run Tests
        run: |
            # Simulate a test that fails
            exit 1  # Change this with your actual test command
  
      - name: Take a screenshot of failure
        if: failure()  # Only run if the previous step fails
        run: |
            mkdir -p screenshots
            echo "Taking a screenshot..."
            python test_google.py  # Ensure this script handles dynamic filenames
            echo "Screenshot taken and saved in the screenshots directory."
  
      - name: Upload screenshots
        id: upload_screenshots
        if: failure()  # Only upload if the previous step fails
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
            name: screenshots
            path: screenshots/
            retention-days: 7  # Keep for 7 days
  
      - name: Notify on failure
        if: failure()
        run: |
            echo "A failure occurred. Check the screenshots here: ${{ steps.upload_screenshots.outputs.artifact_url }}"
            # Integrate with a notification service as needed
  
      - name: Cleanup screenshots
        if: always()  # Run this step regardless of previous step results
        run: |
            echo "Cleaning up screenshots..."
            rm -rf screenshots