name: Run Selenium Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Make sure you have a requirements.txt file
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
        echo "/usr/lib/chromium-browser/chromedriver" >> $GITHUB_PATH
        export DISPLAY=:99.0  # Use Xvfb to run Chrome in a virtual display

    - name: Run tests
      run: |
        # Run pytest and redirect output to log file
        pytest --maxfail=5 --disable-warnings --html=report.html > test_results.log || echo "Tests failed"
        # Print the log output to help diagnose the issue
        cat test_results.log

